// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: common/proto/greeting.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetRequest) Reset() {
	*x = GreetRequest{}
	mi := &file_common_proto_greeting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequest) ProtoMessage() {}

func (x *GreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_greeting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequest.ProtoReflect.Descriptor instead.
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_greeting_proto_rawDescGZIP(), []int{0}
}

func (x *GreetRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *GreetRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GreetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetResponse) Reset() {
	*x = GreetResponse{}
	mi := &file_common_proto_greeting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetResponse) ProtoMessage() {}

func (x *GreetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_greeting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetResponse.ProtoReflect.Descriptor instead.
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_greeting_proto_rawDescGZIP(), []int{1}
}

func (x *GreetResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_common_proto_greeting_proto protoreflect.FileDescriptor

const file_common_proto_greeting_proto_rawDesc = "" +
	"\n" +
	"\x1bcommon/proto/greeting.proto\"@\n" +
	"\fGreetRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\rGreetResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply29\n" +
	"\x0fGreetingService\x12&\n" +
	"\x05Greet\x12\r.GreetRequest\x1a\x0e.GreetResponseB\x14Z\x12ignis/common/protob\x06proto3"

var (
	file_common_proto_greeting_proto_rawDescOnce sync.Once
	file_common_proto_greeting_proto_rawDescData []byte
)

func file_common_proto_greeting_proto_rawDescGZIP() []byte {
	file_common_proto_greeting_proto_rawDescOnce.Do(func() {
		file_common_proto_greeting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_greeting_proto_rawDesc), len(file_common_proto_greeting_proto_rawDesc)))
	})
	return file_common_proto_greeting_proto_rawDescData
}

var file_common_proto_greeting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_greeting_proto_goTypes = []any{
	(*GreetRequest)(nil),  // 0: GreetRequest
	(*GreetResponse)(nil), // 1: GreetResponse
}
var file_common_proto_greeting_proto_depIdxs = []int32{
	0, // 0: GreetingService.Greet:input_type -> GreetRequest
	1, // 1: GreetingService.Greet:output_type -> GreetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_greeting_proto_init() }
func file_common_proto_greeting_proto_init() {
	if File_common_proto_greeting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_greeting_proto_rawDesc), len(file_common_proto_greeting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_greeting_proto_goTypes,
		DependencyIndexes: file_common_proto_greeting_proto_depIdxs,
		MessageInfos:      file_common_proto_greeting_proto_msgTypes,
	}.Build()
	File_common_proto_greeting_proto = out.File
	file_common_proto_greeting_proto_goTypes = nil
	file_common_proto_greeting_proto_depIdxs = nil
}
