// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: common/proto/work.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IgnisService_Greet_FullMethodName = "/IgnisService/Greet"
	IgnisService_Work_FullMethodName  = "/IgnisService/Work"
	IgnisService_Stop_FullMethodName  = "/IgnisService/Stop"
)

// IgnisServiceClient is the client API for IgnisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IgnisServiceClient interface {
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
	Work(ctx context.Context, in *WorkRequest, opts ...grpc.CallOption) (*WorkResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type ignisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIgnisServiceClient(cc grpc.ClientConnInterface) IgnisServiceClient {
	return &ignisServiceClient{cc}
}

func (c *ignisServiceClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, IgnisService_Greet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ignisServiceClient) Work(ctx context.Context, in *WorkRequest, opts ...grpc.CallOption) (*WorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkResponse)
	err := c.cc.Invoke(ctx, IgnisService_Work_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ignisServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, IgnisService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IgnisServiceServer is the server API for IgnisService service.
// All implementations must embed UnimplementedIgnisServiceServer
// for forward compatibility.
type IgnisServiceServer interface {
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
	Work(context.Context, *WorkRequest) (*WorkResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedIgnisServiceServer()
}

// UnimplementedIgnisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIgnisServiceServer struct{}

func (UnimplementedIgnisServiceServer) Greet(context.Context, *GreetRequest) (*GreetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Greet not implemented")
}
func (UnimplementedIgnisServiceServer) Work(context.Context, *WorkRequest) (*WorkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Work not implemented")
}
func (UnimplementedIgnisServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedIgnisServiceServer) mustEmbedUnimplementedIgnisServiceServer() {}
func (UnimplementedIgnisServiceServer) testEmbeddedByValue()                      {}

// UnsafeIgnisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IgnisServiceServer will
// result in compilation errors.
type UnsafeIgnisServiceServer interface {
	mustEmbedUnimplementedIgnisServiceServer()
}

func RegisterIgnisServiceServer(s grpc.ServiceRegistrar, srv IgnisServiceServer) {
	// If the following call panics, it indicates UnimplementedIgnisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IgnisService_ServiceDesc, srv)
}

func _IgnisService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IgnisServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IgnisService_Greet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IgnisServiceServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IgnisService_Work_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IgnisServiceServer).Work(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IgnisService_Work_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IgnisServiceServer).Work(ctx, req.(*WorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IgnisService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IgnisServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IgnisService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IgnisServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IgnisService_ServiceDesc is the grpc.ServiceDesc for IgnisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IgnisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "IgnisService",
	HandlerType: (*IgnisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _IgnisService_Greet_Handler,
		},
		{
			MethodName: "Work",
			Handler:    _IgnisService_Work_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _IgnisService_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/proto/work.proto",
}
