// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: common/proto/work.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetRequest) Reset() {
	*x = GreetRequest{}
	mi := &file_common_proto_work_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequest) ProtoMessage() {}

func (x *GreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_work_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequest.ProtoReflect.Descriptor instead.
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_work_proto_rawDescGZIP(), []int{0}
}

func (x *GreetRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *GreetRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GreetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetResponse) Reset() {
	*x = GreetResponse{}
	mi := &file_common_proto_work_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetResponse) ProtoMessage() {}

func (x *GreetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_work_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetResponse.ProtoReflect.Descriptor instead.
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_work_proto_rawDescGZIP(), []int{1}
}

func (x *GreetResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type WorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	mi := &file_common_proto_work_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_work_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_work_proto_rawDescGZIP(), []int{2}
}

func (x *WorkRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type WorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           string                 `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=workerId,proto3" json:"workerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkResponse) Reset() {
	*x = WorkResponse{}
	mi := &file_common_proto_work_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkResponse) ProtoMessage() {}

func (x *WorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_work_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkResponse.ProtoReflect.Descriptor instead.
func (*WorkResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_work_proto_rawDescGZIP(), []int{3}
}

func (x *WorkResponse) GetAck() string {
	if x != nil {
		return x.Ack
	}
	return ""
}

func (x *WorkResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_common_proto_work_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_work_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_work_proto_rawDescGZIP(), []int{4}
}

func (x *StopRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           string                 `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_common_proto_work_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_work_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_work_proto_rawDescGZIP(), []int{5}
}

func (x *StopResponse) GetAck() string {
	if x != nil {
		return x.Ack
	}
	return ""
}

var File_common_proto_work_proto protoreflect.FileDescriptor

const file_common_proto_work_proto_rawDesc = "" +
	"\n" +
	"\x17common/proto/work.proto\"@\n" +
	"\fGreetRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\rGreetResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"%\n" +
	"\vWorkRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\"<\n" +
	"\fWorkResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\tR\x03ack\x12\x1a\n" +
	"\bworkerId\x18\x02 \x01(\tR\bworkerId\")\n" +
	"\vStopRequest\x12\x1a\n" +
	"\bworkerId\x18\x01 \x01(\tR\bworkerId\" \n" +
	"\fStopResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\tR\x03ack2\x80\x01\n" +
	"\fIgnisService\x12&\n" +
	"\x05Greet\x12\r.GreetRequest\x1a\x0e.GreetResponse\x12#\n" +
	"\x04Work\x12\f.WorkRequest\x1a\r.WorkResponse\x12#\n" +
	"\x04Stop\x12\f.StopRequest\x1a\r.StopResponseB\x14Z\x12ignis/common/protob\x06proto3"

var (
	file_common_proto_work_proto_rawDescOnce sync.Once
	file_common_proto_work_proto_rawDescData []byte
)

func file_common_proto_work_proto_rawDescGZIP() []byte {
	file_common_proto_work_proto_rawDescOnce.Do(func() {
		file_common_proto_work_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_work_proto_rawDesc), len(file_common_proto_work_proto_rawDesc)))
	})
	return file_common_proto_work_proto_rawDescData
}

var file_common_proto_work_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_proto_work_proto_goTypes = []any{
	(*GreetRequest)(nil),  // 0: GreetRequest
	(*GreetResponse)(nil), // 1: GreetResponse
	(*WorkRequest)(nil),   // 2: WorkRequest
	(*WorkResponse)(nil),  // 3: WorkResponse
	(*StopRequest)(nil),   // 4: StopRequest
	(*StopResponse)(nil),  // 5: StopResponse
}
var file_common_proto_work_proto_depIdxs = []int32{
	0, // 0: IgnisService.Greet:input_type -> GreetRequest
	2, // 1: IgnisService.Work:input_type -> WorkRequest
	4, // 2: IgnisService.Stop:input_type -> StopRequest
	1, // 3: IgnisService.Greet:output_type -> GreetResponse
	3, // 4: IgnisService.Work:output_type -> WorkResponse
	5, // 5: IgnisService.Stop:output_type -> StopResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_work_proto_init() }
func file_common_proto_work_proto_init() {
	if File_common_proto_work_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_work_proto_rawDesc), len(file_common_proto_work_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_work_proto_goTypes,
		DependencyIndexes: file_common_proto_work_proto_depIdxs,
		MessageInfos:      file_common_proto_work_proto_msgTypes,
	}.Build()
	File_common_proto_work_proto = out.File
	file_common_proto_work_proto_goTypes = nil
	file_common_proto_work_proto_depIdxs = nil
}
